version: 1
disable_existing_loggers: False

formatters:
  detailed:
    format: '%(asctime)s - %(name)s - %(filename)s - %(levelname)s - %(message)s'
  brief:
    format: '%(levelname)s - %(message)s'

handlers:
  file:
    class: logging.handlers.RotatingFileHandler  # Use RotatingFileHandler to limit file size
    level: DEBUG
    formatter: detailed
    filename: logs/preprocessing.log # set log name
    mode: a  # Append new entries to log file
    encoding: utf-8
    maxBytes: 10485760  # Maximum size in bytes before rotating (here: 10MB)
    backupCount: 5  # Keep 5 backup files before overwriting the oldest

  console:
    class: logging.StreamHandler
    level: INFO
    formatter: brief

loggers:
  preprocessing_logger:
    level: INFO
    handlers: [ file, console ]
    propagate: False

root:
  level: DEBUG
  handlers: [ file, console ]